import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Carpool buddy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <head>
              <!-- Hotjar Tracking Code for https://carpool-buddy-86e69.web.app/ -->
              <script>
                  (function(h,o,t,j,a,r){
                      h.hj = h.hj || function () { (h.hj.q = h.hj.q || []).push(arguments) };
                  h._hjSettings={hjid:3761885,hjsv:6};
                  a=o.getElementsByTagName('head')[0];
                  r=o.createElement('script');r.async=1;
                  r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                  a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
              </script>          </head>
          <!-- Google tag (gtag.js) -->
          <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZNSJ8P4DY4"></script>
          <script>
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'G-ZNSJ8P4DY4');
          </script>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
